title: Style Revolution
description: "Journal des Dames et des Modes"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude: [Gemfile*, node_modules, vendor, Rakefile, README*, spec]

collections:
  pages:
    output: true
  exhibits:
    output: true
    lunr_index:
      content: true
      fields: [title, student]
  plates:
    output: true
    iiif: true
    source: plates.csv
    directory: plates
    layout: plate-page
    lunr_index:
      content: false
      fields: [title, _date, caption, translation, student]

# search tests
quoll:
  full:
    page: search
    terms:
      - napoleon
      - rose
      - crêpe

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
