title: Style Revolution
description: "Journal des Dames et des Modes"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# build settings
theme: minima
markdown: kramdown
permalink: pretty
exclude: [Gemfile*, node_modules, vendor, Rakefile, README*, spec]
lunr_language: true

# collection settings
collections:
  pages:
    output: true
  exhibits:
    output: true
    lunr_index:
      content: true
      fields: [title, student]
  plates:
    output: true
    iiif: true
    keep_order: true
    source: plates.csv
    layout: plate-page
    lunr_index:
      content: false
      fields: [title, _date, caption, translation, student]

# search tests
quoll:
  full:
    page: search
    terms: [turban, cheveux, crêpe, rose]

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
