title: style revolution plates
description: >- #
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude: [Gemfile*, node_modules, vendor, Rakefile]

collections:
  iiif:
    output: true
  pages:
    output: true
  plates:
    output: true
    source: plates.csv
    key: plate
    directory: plates
    layout: plate-page

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
