title: Style Revolution
description: "Journal des Dames et des Modes"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
permalink: pretty

exclude: [Gemfile*, node_modules, vendor, Rakefile, README*]

collections:
  pages:
    output: true
  plates:
    output: true
    source: plates.csv
    directory: plates
    layout: plate-page

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

lunr:
  content: true
  meta:
    - dir: "_plates"
      permalink: "/plates"
      fields:
        - title
        - date
        - caption
        - translation
    - dir: "_pages"
      permalink: ""
      fields:
        - title
